-- Baratheon dynasty seed. Idempotent UPSERT by slug; lineage is wired separately.

INSERT INTO member (slug, name, epithet, house_id, gender, status, is_bastard, born_year, died_year, culture, notable_for)
VALUES
 ('argella-durrandon','Argella Durrandon',NULL,NULL,'female','dead',0,NULL,NULL,'Stormlander','Daughter of Argilac the Arrogant; last Durrandon heir and wife of Orys Baratheon.'),
 ('argilac-durrandon','Argilac Durrandon','the Arrogant',NULL,'male','dead',0,NULL,-2,'Stormlander','Last Storm King, slain by Orys Baratheon during Aegon''s Conquest.'),
 ('orys-baratheon','Orys Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,NULL,'Valyrian','Founder of House Baratheon and first Lord of Storm''s End.'),
 ('davos-baratheon','Davos Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,NULL,'Stormlander','Son of Orys and Argella Baratheon.'),
 ('raymont-baratheon','Raymont Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,NULL,'Stormlander','Son of Orys and Argella Baratheon.'),
 ('rogar-baratheon','Rogar Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,NULL,'Stormlander','Lord of Storm''s End and Hand to Jaehaerys I; husband of Queen Alyssa Velaryon.'),
 ('alyssa-velaryon','Alyssa Velaryon',NULL,NULL,'female','dead',0,7,54,'Valyrian','Mother of Aenys I; later wife of Rogar Baratheon.'),
 ('boremund-baratheon','Boremund Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,129,'Stormlander','Lord of Storm''s End and father of Borros; cousin to Rhaenys Targaryen.'),
 ('borros-baratheon','Borros Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,131,'Stormlander','Lord of Storm''s End during the Dance, supporter of Aegon II.'),
 ('eloris-baratheon','Eloris Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'female','dead',0,NULL,NULL,'Stormlander','Daughter of Borros Baratheon.'),
 ('cassandra-baratheon','Cassandra Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'female','dead',0,NULL,NULL,'Stormlander','Daughter of Borros Baratheon and briefly proposed bride of Aegon II.'),
 ('maris-baratheon','Maris Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'female','dead',0,NULL,NULL,'Stormlander','Sharp-tongued daughter of Borros who mocked Aemond Targaryen at Storm''s End.'),
 ('floris-baratheon','Floris Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'female','dead',0,NULL,NULL,'Stormlander','Daughter of Borros Baratheon.'),
 ('lyonel-baratheon','Lyonel Baratheon','the Laughing Storm',(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,NULL,'Stormlander','Lord of Storm''s End who rebelled briefly after Prince Duncan broke his betrothal.'),
 ('ormund-baratheon','Ormund Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,NULL,260,'Stormlander','Lord of Storm''s End, Hand of the King, and commander in the War of the Ninepenny Kings.'),
 ('steffon-baratheon','Steffon Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,246,278,'Stormlander','Lord of Storm''s End and father of Robert, Stannis, and Renly.'),
 ('cassana-estermont','Cassana Estermont',NULL,NULL,'female','dead',0,NULL,278,'Stormlander','Wife of Steffon Baratheon; drowned with him in Shipbreaker Bay.'),
 ('robert-baratheon','Robert Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,262,298,'Stormlander','King after Robert''s Rebellion; first Baratheon king on the Iron Throne.'),
 ('stannis-baratheon','Stannis Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','alive',0,264,NULL,'Stormlander','Lord of Dragonstone and claimant after Robert''s death.'),
 ('renly-baratheon','Renly Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,277,299,'Stormlander','Lord of Storm''s End who crowned himself during the War of the Five Kings.'),
 ('selyse-florent','Selyse Florent',NULL,NULL,'female','alive',0,NULL,NULL,'Reach','Wife of Stannis Baratheon and mother of Shireen.'),
 ('shireen-baratheon','Shireen Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'female','alive',0,289,NULL,'Stormlander','Only child of Stannis and Selyse Baratheon.'),
 ('mya-stone','Mya Stone',NULL,NULL,'female','alive',1,279,NULL,'Vale','Bastard daughter of Robert Baratheon in the Vale.'),
 ('gendry','Gendry',NULL,NULL,'male','alive',1,284,NULL,'Crownlander','Bastard son of Robert Baratheon raised in King''s Landing.'),
 ('edric-storm','Edric Storm',NULL,NULL,'male','alive',1,287,NULL,'Stormlander','Acknowledged bastard son of Robert Baratheon and Delena Florent.'),
 ('barra','Barra',NULL,NULL,'female','dead',1,298,299,'Crownlander','Infant bastard daughter of Robert Baratheon, murdered in King''s Landing.'),
 ('delena-florent','Delena Florent',NULL,NULL,'female','alive',0,NULL,NULL,'Reach','Mother of Edric Storm.'),
 ('margaery-tyrell','Margaery Tyrell',NULL,(SELECT id FROM house WHERE slug='tyrell'),'female','dead',0,283,300,'Reach','Bride of Renly, Joffrey, and Tommen; central to the Tyrell alliance.')
ON CONFLICT(slug) DO UPDATE SET
  name=excluded.name,
  epithet=COALESCE(excluded.epithet, member.epithet),
  house_id=COALESCE(excluded.house_id, member.house_id),
  gender=excluded.gender,
  status=excluded.status,
  is_bastard=excluded.is_bastard,
  born_year=COALESCE(excluded.born_year, member.born_year),
  died_year=COALESCE(excluded.died_year, member.died_year),
  culture=COALESCE(excluded.culture, member.culture),
  notable_for=COALESCE(excluded.notable_for, member.notable_for),
  updated_at=(cast(unixepoch('subsecond') * 1000 as integer));
