-- Lannister lineage seed: Age of Heroes through the main saga.
-- Idempotent: UPSERT by slug. Parent links are applied in lannister-02-lineage.sql.
-- Year epoch: negative = Before Conquest (BC), positive = After Conquest (AC).

INSERT INTO member (slug, name, epithet, house_id, gender, status, is_bastard, born_year, died_year, culture, notable_for)
VALUES
 -- Founding and kings of the Rock
 ('lann-the-clever','Lann the Clever',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'First Men','Legendary trickster and founding ancestor of House Lannister.'),
 ('loreon-i-lannister','Loreon I Lannister','the Lion',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'First Men','First true known Lannister King of the Rock.'),
 ('tybolt-lannister-thunderbolt','Tybolt Lannister','the Thunderbolt',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'First Men','King of the Rock who fought the first Andal adventurers in the westerlands.'),
 ('tyrion-iii-lannister','Tyrion III Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'First Men','King of the Rock who took Andal sons and daughters as wards instead of continuing open war.'),
 ('gerold-ii-lannister','Gerold II Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'First Men','Son of Tyrion III; continued his father''s accommodation of Andal invaders.'),
 ('gerold-iii-lannister','Gerold III Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'First Men','King of the Rock who died without male issue.'),
 ('lannister-daughter-of-gerold-iii','Daughter of Gerold III Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','dead',0,NULL,NULL,'First Men','Only daughter of Gerold III; her marriage carried the Rock to Joffrey Lydden.'),
 ('joffrey-lydden','Joffrey Lydden',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','Andal knight who married Gerold III''s daughter and took the Lannister name.'),
 ('cerion-lannister','Cerion Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','King of the Rock who extended Lannister rule toward the Golden Tooth.'),
 ('tommen-i-lannister','Tommen I Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','King of the Rock who built a great fleet and brought Fair Isle into the realm.'),
 ('lancel-i-lannister','Lancel I Lannister','the Lion',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','King of the Rock who campaigned against House Gardener.'),
 ('loreon-iii-lannister','Loreon III Lannister','the Limp',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','Son of Lancel I who lost his father''s gains in the Reach.'),
 ('gerold-the-great-lannister','Gerold Lannister','the Great',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','King of the Rock who raided the Iron Islands and returned with hostages.'),
 ('lancel-iv-lannister','Lancel IV Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','King of the Rock killed at Red Lake during war with the Reach.'),
 ('lelia-lannister','Lelia Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','dead',0,NULL,NULL,'Andal','Lannister queen of the Iron Islands through marriage to Harmund II Hoare.'),
 ('tommen-ii-lannister','Tommen II Lannister','the Lion King',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Andal','King of the Rock who vanished in Valyria with Brightroar.'),

 -- Targaryen era
 ('loren-i-lannister','Loren I Lannister','the Last',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Westermen','Last King of the Rock; bent the knee after the Field of Fire.'),
 ('lyman-lannister','Lyman Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,59,'Westermen','Lord of Casterly Rock during the Faith Militant uprising; died in the Shivers.'),
 ('jocasta-tarbeck','Jocasta Tarbeck',NULL,NULL,'female','dead',0,NULL,NULL,'Westermen','Wife of Lord Lyman Lannister.'),
 ('tyler-hill','Tyler Hill',NULL,NULL,'male','dead',1,NULL,NULL,'Westermen','Bastard son of Lyman Lannister who supported Aegon the Uncrowned.'),
 ('tymond-lannister','Tymond Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Westermen','Heir to Casterly Rock during Jaehaerys I''s reign; attended the Great Council of 101 AC.'),
 ('jason-lannister-dance','Jason Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,130,'Westermen','Lord of Casterly Rock during the Dance; declared for Aegon II and died at the Red Fork.'),
 ('tyland-lannister','Tyland Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,133,'Westermen','Twin of Jason; master of ships, master of coin, and Hand of King Aegon III.'),
 ('johanna-westerling','Johanna Westerling',NULL,NULL,'female','dead',0,NULL,NULL,'Westermen','Widow of Jason Lannister and regent of Casterly Rock for her son Loreon.'),
 ('loreon-lannister-son-of-jason','Loreon Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,126,NULL,'Westermen','Young Lord of Casterly Rock after Jason''s death in the Dance.'),
 ('cerelle-lannister-daughter-of-jason','Cerelle Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','dead',0,NULL,NULL,'Westermen','Daughter of Jason and Johanna, considered as a possible bride for Aegon III.'),
 ('tyshara-lannister','Tyshara Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','dead',0,NULL,NULL,'Westermen','Daughter of Jason and Johanna, considered as a possible bride for Aegon III.'),
 ('erwin-lannister','Erwin Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,132,'Westermen','Commanded a failed naval attack against Dalton Greyjoy at Fair Isle.'),

 -- Late Targaryen era into Tywin's generation
 ('damon-lannister-grey-lion','Damon Lannister','the Grey Lion',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,209,'Westermen','Lord of Casterly Rock during Daeron II''s reign; loyalist in the First Blackfyre Rebellion.'),
 ('cerissa-brax','Cerissa Brax',NULL,NULL,'female','dead',0,NULL,NULL,'Westermen','Wife of Damon Lannister and mother of Tybolt and Gerold.'),
 ('tybolt-lannister-son-of-damon','Tybolt Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Westermen','Eldest son of Damon; Lord of Casterly Rock in the reign of Aerys I.'),
 ('teora-kyndall','Teora Kyndall',NULL,NULL,'female','dead',0,NULL,NULL,'Westermen','Wife of Tybolt Lannister and mother of Lady Cerelle.'),
 ('cerelle-lannister-lady-of-casterly-rock','Cerelle Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','dead',0,NULL,NULL,'Westermen','Only child of Tybolt and Lady of Casterly Rock; died young under suspicious circumstances.'),
 ('gerold-lannister-golden','Gerold Lannister','the Golden',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Westermen','Younger son of Damon; prosperous Lord of Casterly Rock and father of Tytos.'),
 ('alysanne-farman','Alysanne Farman',NULL,NULL,'female','dead',0,NULL,NULL,'Westermen','First wife of Gerold the Golden.'),
 ('rohanne-webber','Rohanne Webber',NULL,NULL,'female','dead',0,NULL,NULL,'Reach','Second wife of Gerold the Golden and mother of his children.'),
 ('tywald-lannister','Tywald Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,236,'Westermen','Eldest son of Gerold the Golden; died from wounds after the Battle of Wendwater Bridge.'),
 ('tion-lannister-son-of-gerold','Tion Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,236,'Westermen','Twin of Tywald; killed at the Battle of Wendwater Bridge.'),
 ('tytos-lannister','Tytos Lannister','the Toothless Lion',(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,220,267,'Westermen','Lord of Casterly Rock whose weakness allowed vassals to defy the Lannisters.'),
 ('jeyne-marbrand','Jeyne Marbrand',NULL,NULL,'female','dead',0,NULL,NULL,'Westermen','Wife of Tytos Lannister and mother of Tywin, Kevan, Genna, Tygett, and Gerion.'),
 ('jason-lannister-son-of-gerold','Jason Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,NULL,'Westermen','Fourth son of Gerold the Golden; commander of westermen in the War of the Ninepenny Kings.'),
 ('marla-prester','Marla Prester',NULL,NULL,'female','dead',0,NULL,NULL,'Westermen','Wife of Jason Lannister and mother of Joanna and Stafford.'),
 ('joanna-lannister','Joanna Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','dead',0,NULL,273,'Westermen','Wife and cousin of Tywin Lannister; died giving birth to Tyrion.'),
 ('stafford-lannister','Stafford Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,NULL,299,'Westermen','Brother of Joanna Lannister; slain at the Battle of Oxcross.'),

 -- Main saga branch
 ('tywin-lannister','Tywin Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,242,300,'Westermen','Lord of Casterly Rock, Warden of the West, and Hand of the King; patriarch of the main-saga Lannisters.'),
 ('kevan-lannister','Kevan Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,244,300,'Westermen','Tywin''s reliable brother; later Lord Regent and Protector of the Realm for Tommen I.'),
 ('genna-lannister','Genna Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','alive',0,245,NULL,'Westermen','Daughter of Tytos and Jeyne; married to Emmon Frey.'),
 ('tygett-lannister','Tygett Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,250,285,'Westermen','Younger brother of Tywin; died of a pox.'),
 ('gerion-lannister','Gerion Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','unknown',0,255,NULL,'Westermen','Youngest son of Tytos; vanished in Essos searching for Brightroar.'),
 ('dorna-swyft','Dorna Swyft',NULL,NULL,'female','alive',0,NULL,NULL,'Westermen','Wife of Kevan Lannister.'),
 ('darlessa-marbrand','Darlessa Marbrand',NULL,NULL,'female','alive',0,NULL,NULL,'Westermen','Wife of Tygett Lannister.'),
 ('emmon-frey','Emmon Frey',NULL,NULL,'male','alive',0,NULL,NULL,'Riverlands','Husband of Genna Lannister and later Lord of Riverrun.'),
 ('cersei-lannister','Cersei Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','alive',0,266,NULL,'Westermen','Twin of Jaime; queen to Robert I and later Lady of Casterly Rock.'),
 ('jaime-lannister','Jaime Lannister','the Kingslayer',(SELECT id FROM house WHERE slug='lannister'),'male','alive',0,266,NULL,'Westermen','Twin of Cersei; Kingsguard knight who slew Aerys II during the Sack of King''s Landing.'),
 ('tyrion-lannister','Tyrion Lannister','the Imp',(SELECT id FROM house WHERE slug='lannister'),'male','alive',0,273,NULL,'Westermen','Youngest child of Tywin and Joanna; former acting Hand and claimant to Casterly Rock.'),
 ('lancel-lannister','Lancel Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','alive',0,282,NULL,'Westermen','Eldest son of Kevan; former squire to King Robert and later Warrior''s Son.'),
 ('willem-lannister','Willem Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','dead',0,285,299,'Westermen','Son of Kevan; murdered at Riverrun on Rickard Karstark''s orders.'),
 ('martyn-lannister','Martyn Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','alive',0,285,NULL,'Westermen','Son of Kevan and twin of Willem.'),
 ('janei-lannister','Janei Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','alive',0,NULL,NULL,'Westermen','Daughter of Kevan and Dorna Swyft.'),
 ('tyrek-lannister','Tyrek Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','unknown',0,286,NULL,'Westermen','Son of Tygett; vanished during the bread riots in King''s Landing.'),
 ('joy-hill','Joy Hill',NULL,NULL,'female','alive',1,286,NULL,'Westermen','Bastard daughter of Gerion Lannister.'),
 ('daven-lannister','Daven Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'male','alive',0,NULL,NULL,'Westermen','Son of Stafford; named Warden of the West after Tywin''s death.'),
 ('cerenna-lannister','Cerenna Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','alive',0,NULL,NULL,'Westermen','Daughter of Stafford Lannister.'),
 ('myrielle-lannister','Myrielle Lannister',NULL,(SELECT id FROM house WHERE slug='lannister'),'female','alive',0,NULL,NULL,'Westermen','Daughter of Stafford Lannister.'),

 -- Directly connected non-Lannister spouses and children
 ('robert-baratheon','Robert Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,262,298,'Stormlander','King after Robert''s Rebellion; husband of Cersei Lannister.'),
 ('joffrey-baratheon','Joffrey Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,286,300,'Westermen','Publicly Robert''s heir; secretly the son of Jaime and Cersei.'),
 ('myrcella-baratheon','Myrcella Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'female','alive',0,290,NULL,'Westermen','Daughter of Jaime and Cersei, publicly presented as Robert''s child.'),
 ('tommen-baratheon','Tommen Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','alive',0,291,NULL,'Westermen','Younger son of Jaime and Cersei, crowned after Joffrey''s death.'),
 ('sansa-stark','Sansa Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'female','alive',0,286,NULL,'Northmen','Daughter of Eddard Stark; forced into marriage with Tyrion Lannister.'),
 ('rickard-karstark','Rickard Karstark',NULL,NULL,'male','dead',0,NULL,299,'Northmen','Lord of Karhold, executed by Robb Stark after murdering Willem Lannister and Tion Frey.'),
 ('varys','Varys',NULL,NULL,'male','alive',0,NULL,NULL,NULL,'Master of whisperers who murdered Kevan Lannister to destabilize the realm.'),
 ('tysha','Tysha',NULL,NULL,'female','unknown',0,NULL,NULL,NULL,'First wife of Tyrion Lannister.'),
 ('ermesande-hayford','Ermesande Hayford',NULL,NULL,'female','alive',0,299,NULL,'Crownlander','Infant Lady of Hayford, wed to Tyrek Lannister.')
ON CONFLICT(slug) DO UPDATE SET
  name=excluded.name,
  epithet=COALESCE(excluded.epithet, member.epithet),
  house_id=COALESCE(excluded.house_id, member.house_id),
  gender=excluded.gender,
  status=excluded.status,
  is_bastard=excluded.is_bastard,
  born_year=COALESCE(excluded.born_year, member.born_year),
  died_year=COALESCE(excluded.died_year, member.died_year),
  culture=COALESCE(excluded.culture, member.culture),
  notable_for=COALESCE(excluded.notable_for, member.notable_for),
  updated_at=(cast(unixepoch('subsecond') * 1000 as integer));
