-- Martell dynasty seed. Idempotent UPSERT by slug; lineage is wired separately.

INSERT INTO member (slug, name, epithet, house_id, gender, status, is_bastard, born_year, died_year, culture, notable_for)
VALUES
 ('nymeria','Nymeria',NULL,(SELECT id FROM house WHERE slug='martell'),'female','dead',0,NULL,NULL,'Rhoynar','Rhoynar warrior queen who joined Mors Martell and unified Dorne.'),
 ('mors-martell','Mors Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','dead',0,NULL,NULL,'Dornish','Lord of the Sandship and husband of Nymeria.'),
 ('morgan-martell','Morgan Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','dead',0,NULL,NULL,'Dornish','Son of Mors Martell and Nymeria.'),
 ('myria-martell-nymerias-daughter','Myria Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'female','dead',0,NULL,NULL,'Dornish','Daughter and successor of Nymeria.'),
 ('meria-martell','Meria Martell','the Yellow Toad of Dorne',(SELECT id FROM house WHERE slug='martell'),'female','dead',0,NULL,13,'Dornish','Princess of Dorne who resisted Aegon''s Conquest.'),
 ('nymor-martell','Nymor Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','dead',0,NULL,NULL,'Dornish','Prince of Dorne who negotiated peace after the First Dornish War.'),
 ('deria-martell','Deria Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'female','dead',0,NULL,NULL,'Dornish','Daughter of Nymor who carried peace terms to King''s Landing.'),
 ('mara-martell','Mara Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'female','dead',0,NULL,NULL,'Dornish','Martell princess married to Daeron I''s ally Baelor Targaryen in some peace proposals.'),
 ('moriah-martell','Moriah Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'female','dead',0,NULL,NULL,'Dornish','Ruling Princess of Dorne during Daeron II''s marriage alliance era.'),
 ('myriah-martell','Myriah Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'female','dead',0,152,209,'Dornish','Dornish princess married to Daeron II, bringing Dorne into the realm.'),
 ('maron-martell','Maron Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','dead',0,NULL,NULL,'Dornish','Prince of Dorne who married Daenerys Targaryen as Dorne joined the Seven Kingdoms.'),
 ('daenerys-targaryen-princess','Daenerys Targaryen',NULL,(SELECT id FROM house WHERE slug='targaryen'),'female','dead',0,172,NULL,'Valyrian','Daughter of Daeron II, married to Maron Martell.'),
 ('lewyn-martell','Lewyn Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','dead',0,NULL,283,'Dornish','Kingsguard knight and uncle of Doran, Elia, and Oberyn; died at the Trident.'),
 ('doran-martell','Doran Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','alive',0,247,NULL,'Dornish','Prince of Dorne during the main saga.'),
 ('mellario-of-norvos','Mellario of Norvos',NULL,NULL,'female','alive',0,NULL,NULL,'Norvoshi','Estranged wife of Doran Martell.'),
 ('elia-martell','Elia Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'female','dead',0,257,283,'Dornish','Wife of Rhaegar Targaryen, murdered during the Sack of King''s Landing.'),
 ('oberyn-martell','Oberyn Martell','the Red Viper',(SELECT id FROM house WHERE slug='martell'),'male','dead',0,258,300,'Dornish','Prince of Dorne, famed fighter, and father of the Sand Snakes.'),
 ('rhaegar-targaryen','Rhaegar Targaryen',NULL,(SELECT id FROM house WHERE slug='targaryen'),'male','dead',0,259,283,'Valyrian','Prince of Dragonstone and husband of Elia Martell.'),
 ('arianne-martell','Arianne Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'female','alive',0,276,NULL,'Dornish','Heir to Dorne and daughter of Doran Martell.'),
 ('quentyn-martell','Quentyn Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','dead',0,281,300,'Dornish','Son of Doran, sent east to seek Daenerys Targaryen.'),
 ('trystane-martell','Trystane Martell',NULL,(SELECT id FROM house WHERE slug='martell'),'male','alive',0,287,NULL,'Dornish','Youngest child of Doran Martell, betrothed to Myrcella Baratheon.'),
 ('rhaenys-targaryen-younger','Rhaenys Targaryen',NULL,(SELECT id FROM house WHERE slug='targaryen'),'female','dead',0,280,283,'Valyrian','Daughter of Rhaegar and Elia, murdered in King''s Landing.'),
 ('aegon-targaryen-son','Aegon Targaryen',NULL,(SELECT id FROM house WHERE slug='targaryen'),'male','dead',0,281,283,'Valyrian','Infant son of Rhaegar and Elia, murdered in King''s Landing.'),
 ('myrcella-baratheon','Myrcella Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'female','alive',0,290,NULL,'Westermen','Betrothed to Trystane Martell.'),
 ('ellaria-sand','Ellaria Sand',NULL,NULL,'female','alive',1,NULL,NULL,'Dornish','Paramour of Oberyn Martell.'),
 ('obara-sand','Obara Sand',NULL,NULL,'female','alive',1,271,NULL,'Dornish','Eldest Sand Snake, daughter of Oberyn.'),
 ('nymeria-sand','Nymeria Sand','Lady Nym',NULL,'female','alive',1,273,NULL,'Dornish','Sand Snake, daughter of Oberyn.'),
 ('tyene-sand','Tyene Sand',NULL,NULL,'female','alive',1,276,NULL,'Dornish','Sand Snake, daughter of Oberyn.'),
 ('sarella-sand','Sarella Sand',NULL,NULL,'female','alive',1,280,NULL,'Dornish','Sand Snake, daughter of Oberyn.')
ON CONFLICT(slug) DO UPDATE SET
  name=excluded.name,
  epithet=COALESCE(excluded.epithet, member.epithet),
  house_id=COALESCE(excluded.house_id, member.house_id),
  gender=excluded.gender,
  status=excluded.status,
  is_bastard=excluded.is_bastard,
  born_year=COALESCE(excluded.born_year, member.born_year),
  died_year=COALESCE(excluded.died_year, member.died_year),
  culture=COALESCE(excluded.culture, member.culture),
  notable_for=COALESCE(excluded.notable_for, member.notable_for),
  updated_at=(cast(unixepoch('subsecond') * 1000 as integer));
