-- Stark dynasty seed. Idempotent UPSERT by slug; lineage is wired separately.

INSERT INTO member (slug, name, epithet, house_id, gender, status, is_bastard, born_year, died_year, culture, notable_for)
VALUES
 ('brandon-the-builder','Brandon Stark','the Builder',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'First Men','Legendary founder of House Stark and builder of Winterfell.'),
 ('bran-the-builder-son','Brandon Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'First Men','Early Stark king in the legendary line of Winterfell.'),
 ('theon-stark','Theon Stark','the Hungry Wolf',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'First Men','Ancient King in the North famed for brutal wars against the Andals and ironborn.'),
 ('brandon-shipwright','Brandon Stark','the Shipwright',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'First Men','King in the North who sailed west and never returned.'),
 ('brandon-burner','Brandon Stark','the Burner',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'First Men','Burned the northern fleet after his father vanished.'),
 ('torrhen-stark','Torrhen Stark','the King Who Knelt',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Last King in the North; bent the knee to Aegon I.'),
 ('brandon-snow','Brandon Snow',NULL,NULL,'male','dead',1,NULL,NULL,'Northmen','Bastard half-brother of Torrhen Stark.'),
 ('walton-stark','Walton Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Lord of Winterfell during Jaehaerys I''s reign.'),
 ('ellard-stark','Ellard Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Lord of Winterfell who attended the Great Council of 101 AC.'),
 ('rickon-stark-father-of-cregan','Rickon Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,121,'Northmen','Father of Cregan Stark.'),
 ('cregan-stark','Cregan Stark','the Old Man of the North',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,108,NULL,'Northmen','Lord of Winterfell during the Dance and the Hour of the Wolf.'),
 ('arra-norrey','Arra Norrey',NULL,NULL,'female','dead',0,NULL,NULL,'Northmen','First wife of Cregan Stark and mother of Rickon.'),
 ('alysanne-blackwood','Alysanne Blackwood','Black Aly',NULL,'female','dead',0,NULL,NULL,'Riverlander','Second wife of Cregan Stark.'),
 ('rickon-stark-son-of-cregan','Rickon Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,121,'Northmen','Son of Cregan and Arra Norrey.'),
 ('jonnel-stark','Jonnel Stark','One-Eye',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Lord of Winterfell, son of Cregan Stark.'),
 ('barthogan-stark','Barthogan Stark','Barth Blacksword',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Lord of Winterfell, son of Cregan Stark.'),
 ('brandon-stark-son-of-cregan','Brandon Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Son of Cregan Stark and ancestor of later Lords of Winterfell.'),
 ('rodwell-stark','Rodwell Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Lord of Winterfell in the early third century AC.'),
 ('beron-stark','Beron Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Lord of Winterfell who fought Dagon Greyjoy.'),
 ('lorna-tyrell','Lorna Tyrell',NULL,(SELECT id FROM house WHERE slug='tyrell'),'female','dead',0,NULL,NULL,'Reach','Wife of Beron Stark.'),
 ('willam-stark','Willam Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,226,'Northmen','Lord of Winterfell killed fighting wildlings.'),
 ('artos-stark','Artos Stark','the Implacable',(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Younger son of Beron who avenged Willam against wildlings.'),
 ('edwyle-stark','Edwyle Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,NULL,'Northmen','Lord of Winterfell and father of Rickard Stark.'),
 ('rickard-stark','Rickard Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,NULL,282,'Northmen','Lord of Winterfell, burned alive by Aerys II.'),
 ('lyarra-stark','Lyarra Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'female','dead',0,NULL,NULL,'Northmen','Wife of Rickard Stark and mother of Brandon, Eddard, Lyanna, and Benjen.'),
 ('brandon-stark-son-of-rickard','Brandon Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,262,282,'Northmen','Heir to Winterfell, strangled by Aerys II.'),
 ('ned-stark','Eddard Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,263,299,'Northmen','Lord of Winterfell and Hand of the King.'),
 ('lyanna-stark','Lyanna Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'female','dead',0,266,283,'Northmen','Sister of Eddard Stark; her disappearance helped trigger Robert''s Rebellion.'),
 ('benjen-stark','Benjen Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','unknown',0,267,NULL,'Northmen','Brother of Eddard Stark and First Ranger of the Night''s Watch.'),
 ('catelyn-tully','Catelyn Tully',NULL,(SELECT id FROM house WHERE slug='tully'),'female','dead',0,264,299,'Riverlander','Wife of Eddard Stark and mother of Robb, Sansa, Arya, Bran, and Rickon.'),
 ('robb-stark','Robb Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','dead',0,283,299,'Northmen','King in the North and Trident.'),
 ('sansa-stark','Sansa Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'female','alive',0,286,NULL,'Northmen','Daughter of Eddard and Catelyn Stark.'),
 ('arya-stark','Arya Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'female','alive',0,289,NULL,'Northmen','Daughter of Eddard and Catelyn Stark.'),
 ('bran-stark','Bran Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','alive',0,290,NULL,'Northmen','Son of Eddard and Catelyn Stark, greenseer north of the Wall.'),
 ('rickon-stark-young','Rickon Stark',NULL,(SELECT id FROM house WHERE slug='stark'),'male','alive',0,295,NULL,'Northmen','Youngest son of Eddard and Catelyn Stark.'),
 ('jon-snow','Jon Snow',NULL,NULL,'male','alive',1,283,NULL,'Northmen','Raised as Eddard Stark''s bastard; true parentage hidden.'),
 ('jeyne-westerling','Jeyne Westerling',NULL,NULL,'female','alive',0,NULL,NULL,'Westermen','Wife of Robb Stark in the books.'),
 ('robert-baratheon','Robert Baratheon',NULL,(SELECT id FROM house WHERE slug='baratheon'),'male','dead',0,262,298,'Stormlander','Foster brother of Eddard Stark.'),
 ('jon-arryn','Jon Arryn',NULL,(SELECT id FROM house WHERE slug='arryn'),'male','dead',0,NULL,298,'Valeman','Foster father of Eddard Stark and Robert Baratheon.')
ON CONFLICT(slug) DO UPDATE SET
  name=excluded.name,
  epithet=COALESCE(excluded.epithet, member.epithet),
  house_id=COALESCE(excluded.house_id, member.house_id),
  gender=excluded.gender,
  status=excluded.status,
  is_bastard=excluded.is_bastard,
  born_year=COALESCE(excluded.born_year, member.born_year),
  died_year=COALESCE(excluded.died_year, member.died_year),
  culture=COALESCE(excluded.culture, member.culture),
  notable_for=COALESCE(excluded.notable_for, member.notable_for),
  updated_at=(cast(unixepoch('subsecond') * 1000 as integer));
